#! /bin/sh
# Version 2018.224.1
# Copyright (c) 2018 Guenther Brunthaler. All rights reserved.
# 
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

set -e
trap 'test $? = 0 || echo "$0 failed" >& 2' 0

while getopts '' opt
do
	case $opt in
		*) false || exit
	esac
done
shift `expr $OPTIND - 1 || :`

for a
do
	if
		c=`command -v -- "$a" 2> /dev/null` \
		&& test "$c" && test -e "$c"
	then
		c=`readlink -f -- "$c"`
		dpkg -S -- "$c" 2> /dev/null && continue
		echo "(not in any locally-installed package): $a"
	else
		echo "(not found at all): $a"
	fi
done | LC_COLLATE=C sort
